/* Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
pentagonal numbers are:

                1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference
are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

import java.util.List;
import java.util.ArrayList;
import java.lang.Math;

public class problem_44 {
  public static void main(String args[]) {
    long smallesDif = Long.MAX_VALUE;
    long num1 = 0l, num2 = 0l;

    List<Long> pentagonalNos = new ArrayList<Long>();
    for(int i = 1; i < 3000; i ++) {
      long num = (i*((3*i)-1))/2;
      pentagonalNos.add(num);
    }

    for(int k = pentagonalNos.size()-1; k >-1 ; k--) {
      long Pk = pentagonalNos.get(k);
      for(int j = 0; j < k; j++) {
        long Pj = pentagonalNos.get(j);
        long sum = Pj + Pk;
        long difference = Math.abs(Pk - Pj);

        if(isPentagonal(sum) && isPentagonal(difference)) {
          if(smallesDif > difference) {
            smallesDif = difference;
            num1 = Pk;  num2 = Pj;
          }
          break;
        }
      }
    }

    System.out.println("The pair of pentagonal numbers, "+num1+" and "+num2+
                        ", have a minimised difference of: " +smallesDif);
  }

  private static boolean isPentagonal(long num) {
    double remainder = (Math.sqrt((24*num)+1.0)+1.0) % 6;
    return (remainder == 0)? true: false;
  }
}