/* The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

import java.lang.Math;

public class problem_12 {
  public static void main(String args[]) {
    int numbOfDivisors = 500, triNo = 0;
    boolean goOn = true;
    for(int i = 1; i<10000000 && goOn == true; i++) {
      triNo += i;
      if(checkNoOfDivisors(triNo, numbOfDivisors)) {
        System.out.println("The first triangle number with " +
            numbOfDivisors+ " divisors is: " +triNo);
        goOn = false;
      }
    }
  }

  private static boolean checkNoOfDivisors(int triNo, int divNo) {
    int noOfDiv = 0;
    for(int i = 1; i<(int) Math.floor(Math.sqrt(triNo)); i++) {
      if(triNo % i == 0)  noOfDiv += 2;
    }
    return ((noOfDiv >= divNo)? true:false);
  }
}
