/* Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

        Triangle        Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
        Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
        Hexagonal 	  	Hn=n(2n−1) 	  	  1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

public class problem_45 {
  public static void main(String args[]) {
    long index = 285;
    long number = 0l;

    while(true) {
      index++;
      long triangleNo = (long) (index*(index+1))/2;
      if(isPentagonal(triangleNo) && isHexagonal(triangleNo)){
        number = triangleNo;
        break;
      }
    }

    System.out.println("The next triangle number that is also pentagonal and hexagonal is: "
                            +number);
  }

  private static boolean isPentagonal(long num) {
    double remainder = (Math.sqrt((24*num)+1.0)+1.0) % 6;
    return (remainder == 0)? true: false;
  }

  private static boolean isHexagonal(long num) {
    double remainder = (Math.sqrt((8*num)+1.0)+1.0) % 4;
    return (remainder == 0)? true: false;
  }
}